<a href="https://colab.research.google.com/github/maxryb2005/lab4/blob/main/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
rand_list = []
n=10
for i in range (n):
  rand_list.append(random.randint(3,9))
print(rand_list)


[8, 7, 6, 9, 5, 7, 5, 6, 4, 7]


In [3]:
res = random.sample(range(1,50),7)
print ("Случайное число: ", str(res))

Случайное число:  [6, 3, 49, 28, 32, 33, 27]


In [4]:
res = [random.randrange(1,50,1) for i in range(7)]
print ("Случайное число: ", str(res))

Случайное число:  [8, 14, 40, 47, 12, 5, 42]


In [5]:
lis = []
for _ in range (10):
  lis.append(random.randint(0,51))
print(lis)

[42, 6, 46, 11, 36, 43, 11, 32, 16, 9]


In [8]:
import numpy
print(list(numpy.random.randint(low=3, high=8, size=10)))
print(list(numpy.random.randint(low = 3,size=5)))

[6, 3, 7, 3, 6, 5, 5, 4, 4, 6]
[0, 0, 0, 1, 0]


In [9]:
print(numpy.random.random_sample(size = 4))
print(numpy.random.random_sample(size = (4,4)))

[0.11343136 0.75960645 0.44760851 0.3903625 ]
[[0.78009297 0.93833501 0.70393763 0.41860409]
 [0.24731162 0.68574005 0.02986875 0.69154861]
 [0.99369319 0.71837024 0.14283533 0.05209827]
 [0.66310653 0.50716031 0.19936207 0.55082855]]
